version: '3'
services:
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile.user_service
    ports:
      - "8005:8005"
    depends_on:
      - postgresql_user_service
    env_file: ".env"

  device_service:
    build:
      context: ./device_service
      dockerfile: Dockerfile.device_service
    ports:
      - "8001:8000"
    depends_on:
      - user_service
      - postgresql_device_service
    environment:
      - POSTGRES_DEVICE_DATABASE_USERNAME=${POSTGRES_DEVICE_DATABASE_USERNAME}
      - POSTGRES_DEVICE_DATABASE_PASSWORD=${POSTGRES_DEVICE_DATABASE_PASSWORD}
      - POSTGRES_DEVICE_DATABASE_NAME=${POSTGRES_DEVICE_DATABASE_NAME}
      - POSTGRES_DEVICE_DATABASE_HOST=${POSTGRES_DEVICE_DATABASE_HOST}
    env_file: ".env"
  
  sensor_data_service:
    build: 
      context: ./sensor_data_service
      dockerfile: Dockerfile.sensor_data_service
    ports:
      - "8006:8006"
    depends_on:
      - mosquitto
      - influxdb
    env_file:
      - ".env"

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - C:/Users/arsen/Documents/SmartFarm/mosquitto/config:/mosquitto/config
      - C:/Users/arsen/Documents/SmartFarm/mosquitto/data:/mosquitto/data
      - C:/Users/arsen/Documents/SmartFarm/mosquitto/log:/mosquitto/log
      - C:/Users/arsen/Documents/SmartFarm/mosquitto/certs:/mosquitto/certs
    env_file: ".env"

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - C:/Users/arsen/Documents/SmartFarm/influxdb/data:/var/lib/influxdb2
      - C:/Users/arsen/Documents/SmartFarm/influxdb/config:/etc/influxdb2
    env_file: ".env"

  postgresql_user_service:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - C:/Users/arsen/Documents/SmartFarm/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER_DATABASE_NAME}

  postgresql_device_service:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DEVICE_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DEVICE_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEVICE_DATABASE_NAME}
    volumes:
      - C:/Users/arsen/Documents/SmartFarm/postgresql_user_database/data:/var/lib/postgresql/data