
FROM python:3.11-slim


WORKDIR /app


COPY rule_service/requirements.txt /app/requirements.txt


RUN pip install --no-cache-dir -r requirements.txt

COPY common ./common


COPY rule_service ./rule_service


ENV PYTHONPATH=/app


EXPOSE 8004


RUN pip install gunicorn
CMD ["gunicorn", "rule_service.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8004"]