
FROM python:3.11-slim


WORKDIR /app


COPY rule_service/requirements.txt /app/requirements.txt


RUN pip install --no-cache-dir -r requirements.txt

COPY common ./common


COPY rule_service ./rule_service


ENV PYTHONPATH=/app


EXPOSE 8004


CMD ["uvicorn", "rule_service.main:app", "--host", "0.0.0.0", "--port", "8004"]