
FROM python:3.11-slim


WORKDIR /app


COPY rule_service/requirements.txt /app/requirements.txt


RUN pip install --no-cache-dir -r requirements.txt

COPY common /app/common


COPY rule_service /app/rule_service


ENV PYTHONPATH=/app


EXPOSE 8007


CMD ["uvicorn", "rule_service.main:app", "--host", "0.0.0.0", "--port", "8007"]