# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container to /app
WORKDIR /app

# 1. Сначала копируем зависимости (для кэширования слоев)
COPY sensor_data_service/requirements.txt /app/requirements.txt

# Install packages
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

# 2. Копируем ОБЩУЮ библиотеку
COPY common ./common

# 3. Копируем код СЕРВИСА
COPY sensor_data_service ./sensor_data_service

# 4. ВАЖНО: Добавляем текущую директорию в PYTHONPATH
ENV PYTHONPATH=/app

# Run the ingestion worker (standalone python script)
CMD ["python", "-m", "sensor_data_service.main_ingestion"]