#!/bin/bash
set -e

# Create roles and databases for the microservices
# The default $POSTGRES_USER will act as the superuser for this container.

# 1. User Service Database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_USER_DATABASE_USERNAME WITH ENCRYPTED PASSWORD '$POSTGRES_USER_DATABASE_PASSWORD';
    CREATE DATABASE $POSTGRES_USER_DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_USER_DATABASE_NAME TO $POSTGRES_USER_DATABASE_USERNAME;
    \c $POSTGRES_USER_DATABASE_NAME
    GRANT ALL ON SCHEMA public TO $POSTGRES_USER_DATABASE_USERNAME;
EOSQL

# 2. Farm Management Service Database (labeled DEVICE in env sometimes, using FARM variables as defined in compose)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_FARM_DATABASE_USERNAME WITH ENCRYPTED PASSWORD '$POSTGRES_FARM_DATABASE_PASSWORD';
    CREATE DATABASE $POSTGRES_FARM_DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_FARM_DATABASE_NAME TO $POSTGRES_FARM_DATABASE_USERNAME;
    \c $POSTGRES_FARM_DATABASE_NAME
    GRANT ALL ON SCHEMA public TO $POSTGRES_FARM_DATABASE_USERNAME;
EOSQL

# 3. Rule Service Database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_RULE_DATABASE_USERNAME WITH ENCRYPTED PASSWORD '$POSTGRES_RULE_DATABASE_PASSWORD';
    CREATE DATABASE $POSTGRES_RULE_DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_RULE_DATABASE_NAME TO $POSTGRES_RULE_DATABASE_USERNAME;
    \c $POSTGRES_RULE_DATABASE_NAME
    GRANT ALL ON SCHEMA public TO $POSTGRES_RULE_DATABASE_USERNAME;
EOSQL

echo "Logical databases and users created successfully."
